### PR TITLE
Use `drush_path` for update tasks

### PR DESCRIPTION
**Pull request by mglaman**
For issue #36

### CODE REVIEW

**Comment by geerlingguy** [comment]
@mglaman - Can you rebase on `master`? The test fail is because of a change there.

Also, I see that I used `{{ drush_path }}` a couple other places, but technically provide no default (yikes!). It's added by the `geerlingguy.drush` role, but it might be good to fallback to `default('drush')` if no `drush_path` is set.

**Comment by mglaman** [comment]
@geerlingguy rebased. I'll admit, figuring out where to put `default('drush')` is above my head. I see `{{ drush_path }}` isused in build makefile as well.

**Comment by geerlingguy** [comment]
No problem, I'll create a follow-up, as this is kinda low priority, since it's highly likely if you use this role, you'll use `geerlingguy.drush` as well and it will never be a problem. Else, you can just set `drush_path` manually if needed.

**Comment by geerlingguy** [comment]
Created a follow-up issue https://github.com/geerlingguy/ansible-role-drupal/issues/39

**Pull request merged**
